name: itcs444_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.4
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  flutter_iconpicker: ^3.2.4
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/